Release
halestudio/hale pull request #1115
Opened 2024-02-22 13:56 UTC by emanuelaepure10

2024-02-22 16:34 UTC, stempler requested changes
Only a small issue related to an accidentally added file - once that is fixed I will merge the PR using a Merge Commit (this will have to be temporarily enabled in the project settings).

2024-02-22 16:34 UTC, stempler commented on ui/plugins/eu.esdihumboldt.hale.ui.index/.project
This project was removed by @florianesser , you probably accidentally added the file because it still existed for you locally.

2024-02-22 20:23 UTC, emanuelaepure10 commented on ui/plugins/eu.esdihumboldt.hale.ui.index/.project
During the merge I was just asked to decide on this file

> ui/plugins/eu.esdihumboldt.hale.ui.index/MANIFEST.MF

2024-02-23 10:01 UTC, merged

2024-02-23 10:11 UTC, emanuelaepure10 commented
@stempler Thank you
Once it is ready I will take the files and update the already drafted release notes.