Remove the GroupPropertyDefinitions from path when using "Add condition context"
halestudio/hale pull request #976
Opened 2022-07-08 13:10 UTC by Flaminietta

The function "Add condition context" does not work if in the filter path are included also GroupPropertyDefinitions (e.g. "choice", "choice_1" or the like). This PR filters them out.

ING-3458

2022-07-20 07:58 UTC, Flaminietta commented
I have addressed your suggestions.

2022-07-20 09:36 UTC, stempler requested changes

2022-07-20 09:36 UTC, stempler commented on ui/plugins/eu.esdihumboldt.hale.ui.filter/src/eu/esdihumboldt/hale/ui/filter/cql/CQLFilterField.java
> +						var.append(".");
> The case that you don't handle here however is that the first element (index 0) could have been a group/choice. In that case you would also not want to add a dot.

This is not solved yet.
If the  first element with index 0 was a group/choice then you would start the string with a dot, which is not correct.

2022-07-20 15:43 UTC, stempler commented on ui/plugins/eu.esdihumboldt.hale.ui.filter/src/eu/esdihumboldt/hale/ui/filter/cql/CQLFilterField.java
> +					if (i != 0 && !stringVar.isEmpty())
`stringVar` will not be initialized yet.
You can do a check on the StringBuilder (`var`) directly. There should be a method where you can check its current length or something like that.

2022-07-21 09:15 UTC, stempler approved these changes

2022-07-21 10:13 UTC, merged